### ISSUE TITLE
SQLSTATE HV000 error when selecting kubernetes_cronjob

### ISSUE THREAD

**Issue by ngirard** [turbot/steampipe-plugin-kubernetes#132] opened 2023-04-18 09:04 UTC
**Describe the bug**
I'm especially interested in the `kubernetes_cronjob` table. Unfortunately I've never managed to get a SELECT upon this table to work since I first tried, 3 or 4 months ago.

**Steampipe version (`steampipe -v`)**
Steampipe v0.20.0-alpha.4

**Plugin version (`steampipe plugin list`)**
Example: v0.18.1

**To reproduce**
```sh
steampipe query 'select * from kubernetes_cronjob;'
```
This produces
```
Error: the server could not find the requested resource (SQLSTATE HV000)
```
followed by an empty table.

**Comment by ngirard** [comment] 2023-04-18 16:15
Well thank you @bigdatasourav for involving yourself into such a great project !

I'm sorry I'm only partially answering your questions, I'll post the rest whenever I can.

Indeed, I just performed a `plugin install` instead of an `update`, I've now updated to v0.18.1 and the behavior is the same.

`kubectl get cronjob xx` returns
```
NAME                   SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
xxx   *[/5](https://file+.vscode-resource.vscode-cdn.net/5) * * * *   False     0        14d             14d
```

and `kubectl version` returns
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux[/amd64](https://file+.vscode-resource.vscode-cdn.net/amd64)"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-08-01T23:56:00Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux[/amd64](https://file+.vscode-resource.vscode-cdn.net/amd64)"}
WARNING: version difference between client (1.26) and server (1.11) exceeds the supported minor version skew of +[/-1](https://file+.vscode-resource.vscode-cdn.net/-1)
```

**Comment by ngirard** [comment] 2023-04-18 16:19
As for Kubernetes, it's hosted on a dedicated machine.

As for the `kubernetes.spc` file, I'm not sure I can get my hands on it.

**Comment by ngirard** [comment] 2023-04-18 16:30
I executed
```
echo "\
kubernetes_cluster_role
kubernetes_cluster_role_binding
kubernetes_config_map
kubernetes_cronjob
kubernetes_custom_resource_definition
kubernetes_daemonset
kubernetes_deployment
kubernetes_endpoint
kubernetes_endpoint_slice
kubernetes_event
kubernetes_horizontal_pod_autoscaler
kubernetes_ingress
kubernetes_job
kubernetes_limit_range
kubernetes_namespace
kubernetes_network_policy
kubernetes_node
kubernetes_persistent_volume
kubernetes_persistent_volume_claim
kubernetes_pod
kubernetes_pod_disruption_budget
kubernetes_pod_security_policy
kubernetes_replicaset
kubernetes_replication_controller
kubernetes_resource_quota
kubernetes_role
kubernetes_role_binding
kubernetes_secret
kubernetes_service
kubernetes_service_account
kubernetes_stateful_set
kubernetes_storage_class" | while read table; do echo -e "\n——— $table\n\n"; steampipe query "select * from ${table} limit 1;"; done
```

and here's the tables that wouldn't pass:
- kubernetes_cronjob (1)
- kubernetes_custom_resource_definition (1)
- kubernetes_endpoint_slice (2)
- kubernetes_ingress (3)
- kubernetes_pod_disruption_budget (1)
- kubernetes_secret (4)

and the associated error messages:
- (1): Error: the server could not find the requested resource (SQLSTATE HV000)
- (2): Error: endpointslices.discovery.k8s.io is forbidden: User "ngirard" cannot list endpointslices.discovery.k8s.io at the cluster scope: no RBAC policy matched (SQLSTATE HV000)
- (3): Error: ingresses.networking.k8s.io is forbidden: User "ngirard" cannot list ingresses.networking.k8s.io at the cluster scope: no RBAC policy matched (SQLSTATE HV000)
- (4): Error: secrets is forbidden: User "ngirard" cannot list secrets at the cluster scope: no RBAC policy matched (SQLSTATE HV000)

**Comment by bigdatasourav** [comment] 2023-04-19 06:06
Thanks, @ngirard, for the quick response; I am still trying to reproduce the above error. Could you please share the Kubernetes version you are using?

**Comment by ngirard** [comment] 2023-04-19 07:22
> Could you please share the Kubernetes version you are using?

Hey @bigdatasourav,
as far as I understand this can be found in the output from `kubectl version`:
```
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-08-01T23:56:00Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux[/amd64](https://file+.vscode-resource.vscode-cdn.net/amd64)"}
```
Please let me know if it suits you, otherwise I'll ask our SREs.

**Comment by bigdatasourav** [comment] 2023-04-19 12:05
Thanks, @ngirard; as I can see, you are using an older version of Kubernetes `v1.11.0+d4cacc0`, which could be the reason for the error, with the latest stable versions, e.g. `v1.24.10`, I could not be able to reproduce that error.

CronJob API version of batch/v1 is fully supported since [v1.21](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#cronjob-v1-batch) only. However, batch/v1beta1 has backward compatibility.

I have raised a draft [PR](https://github.com/turbot/steampipe-plugin-kubernetes/pull/133) with a fix. Please try this and let us know your feedback.

**Comment by ngirard** [comment] 2023-04-19 12:39
@bigdatasourav , thanks you so much for your efforts !

I'm much more of a rustacean than a golanger, but I'll definitely take a stab at the PR since you provided clear instructions for me to compile it.

I'll keep you posted.

**Comment by bigdatasourav** [comment] 2023-04-19 13:49
Unfortunately, CustomResourceDefination API version Apiextensions/V1beta1 does support older Kubernetes versions. Still, it does not support the latest versions like [v1.24](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#customresourcedefinition-v1-apiextensions-k8s-io), so in our table, we have used the API version Apiextensions/V1 which is not compatible with older versions like `v1.11.0+d4cacc0`.

Same with [CronJob](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#cronjob-v1-batch) and [PodDisruptionBudget](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#poddisruptionbudget-v1-policy), they have also removed the API version v1beta1 support in the latest Kubernetes version v1.27.

I will dig it down further to check if we can provide support for both(old + latest).

**Comment by ngirard** [comment] 2023-04-19 14:04
Oh, perhaps I wasn't clear in my feedback: the patch does work for the `kubernetes_cronjob` table, which is the only one I'm interested in !

**Comment by bigdatasourav** [comment] 2023-04-20 12:36
Hey @ngirard,  wanted to follow up on our previous communication regarding our plugin's compatibility with older Kubernetes API versions.

As I  mentioned earlier, our plugin currently supports the v1 API version, which does not support some of the older Kubernetes versions, and while we are constantly working on improving our product's capabilities, we regret to inform you that we do not have any plans to add support for the V1beta1 API version which works with older Kubernetes versions at this time.

I understand that this may be disappointing news, and I apologize for any inconvenience this may cause. However, I want to assure you that we are always open to feedback and suggestions from our users, and we will take your request into consideration as we continue to develop our plugin.

Also, you can continue to use [this](https://github.com/turbot/steampipe-plugin-kubernetes/pull/133) PR if it helps to resolve your problem.

If you have any further questions or concerns, please don't hesitate to reach out to us. We appreciate your support and look forward to continuing to work with you.

**Comment by ngirard** [comment] 2023-04-20 14:51
Hey @bigdatasourav, thanks for the heads up.

Sure, I understand. It won't be a problem at all for me: I'll keep using this PR until we have migrated to a newer version of Kubernetes, which should happen in the forthcoming months.

Thank you again for your efforts !

**Comment by cbruno10** [comment] 2023-05-03 15:11
@ngirard Based on @bigdatasourav 's comment above, I'll be closing this issue as we're not currently planning on supporting older API versions, but if you have anymore questions, feel free to re-open this issue. Thanks!

**Closed by cbruno10** 2023-05-03 15:11 UTC
Labels: bug

**Comment by ngirard** [comment] 2023-05-03 15:30
Sure, @cbruno10 ! Cheers !
