### ISSUE TITLE
current-context is not being honoured in queries

### ISSUE THREAD

**Issue by horrendo** [turbot/steampipe-plugin-kubernetes#180] opened 2023-10-08 18:05 UTC
**Describe the bug**
Our kubernetes (eks) cluster restricts access to the current user to the namespace they have been given access to. We cannot do 'cluster-wide' actions. This essentially renders the kubernetes plugin unusable for us because it doesn't even allow a query to be qualified by namespace. For example:

```
[~/git/unsullied] kc get pods
NAME                                                      READY   STATUS    RESTARTS   AGE
gitlabcom-large-db-gitlab-runner-5b87c48c4-ct5q7          1/1     Running   0          26d
gitlabcom-large-gitlab-runner-7c5bb86985-zc28n            1/1     Running   0          26d
gitlabcom-large-uploader-gitlab-runner-768bb5cdfb-9dwmt   1/1     Running   0          26d
gitlabcom-micro-db-gitlab-runner-59578d556f-mmnz5         1/1     Running   0          26d
gitlabcom-micro-gitlab-runner-fbf7d6f8b-m6vnd             1/1     Running   0          26d
gitlabcom-micro-uploader-gitlab-runner-6d944644bf-bnhch   1/1     Running   0          26d
gitlabcom-xerox-staging-gitlab-runner-6fc68f7876-cpk6d    1/1     Running   0          26d
qa-service-unsullied-5d8f57f9b-2lrk5                      1/1     Running   0          2d15h
qa-service-unsullied-5d8f57f9b-8wbqq                      1/1     Running   0          2d15h
qa-service-unsullied-background-65ddfcb55f-xldbm          1/1     Running   0          2d15h
qa-service-unsullied-redis-cd46cd58f-vjzs8                1/1     Running   0          5d12h
qa-service-unsullied-sqs-9687c986c-4h4sl                  1/1     Running   0          26d
qa-service-unsullied-sqs-9687c986c-qghhs                  1/1     Running   0          26d
qa-ui-xerox-5fcbb47d66-4nsqn                              1/1     Running   0          7d18h
staging-httpbin-httpstatus-8dcf8865-ktjvz                 1/1     Running   0          26d
staging-service-unsullied-background-78fc5bc889-6m7x2     1/1     Running   0          2d15h
staging-service-unsullied-background-78fc5bc889-q98mk     1/1     Running   0          2d15h
staging-service-unsullied-fcbbd465d-j6wkq                 1/1     Running   0          2d15h
staging-service-unsullied-fcbbd465d-knlsh                 1/1     Running   0          2d15h
staging-service-unsullied-redis-568f95bbb8-lh8nv          1/1     Running   0          26d
staging-service-unsullied-sqs-7478b4fcd6-lbcr5            1/1     Running   0          5d12h
staging-ui-xerox-77f84495d8-k4ltv                         1/1     Running   0          2d14h
[~/git/unsullied] grep current-context $KUBECONFIG
current-context: b2bc-staging
[~/git/unsullied] steampipe query "select name from kubernetes_pod where namespace = 'b2bc'"

Error: pods is forbidden: User "b2bc-admin" cannot list resource "pods" in API group "" at the cluster scope (SQLSTATE HV000)

+------+
| name |
+------+
+------+
```

The same behaviour is observed for all kubernetes queries, so this is not limited to `kubernetes_pod`.

**Steampipe version (`steampipe -v`)**
Steampipe v0.21.1

**Plugin version (`steampipe plugin list`)**[~/git/unsullied] steampipe plugin list
```
+---------------------------------------------------+---------+-------------+
| Installed                                         | Version | Connections |
+---------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/aws@latest        | 0.120.2 | aws         |
| hub.steampipe.io/plugins/turbot/kubernetes@latest | 0.25.1  | kubernetes  |
| hub.steampipe.io/plugins/turbot/steampipe@latest  | 0.9.1   | steampipe   |
+---------------------------------------------------+---------+-------------+
```

**To reproduce**
See above. You will of course need a cluster configured with similar security restrictions to ours.

**Expected behavior**
I would like to see it honour the `current-context` in $KUBECONFIG. Maybe this could be a configuration option in `kubernetes.spc`.

**Additional context**
I raised this on the Slack channel and Nathan Wallace confirmed the behaviour and asked me to raise an issue 😄 .

**Comment by beudbeud** [comment] 2023-10-11 12:34
#181

**Comment by pdecat** [comment] 2023-11-07 17:53
#181 does not resolve this issue, see https://github.com/turbot/steampipe-plugin-kubernetes/pull/181#issuecomment-1757653186

**Comment by bigdatasourav** [comment] 2023-11-08 03:00
Hey @pdecat, apologies for the oversight; we will investigate it further.

**Comment by KristjanTammekivi** [comment] 2023-11-22 13:30
Today I updated to 0.25.2 and now it seems to be fixed (at least for me, didn't work yesterday)

**Comment by horrendo** [comment] 2023-11-22 17:55
I just tried upgrading via brew and got told:

`Warning: turbot/tap/steampipe 0.21.1 already installed`

**Comment by bigdatasourav** [comment] 2023-11-22 17:57
@horrendo, please try `steampipe plugin update kubernetes` to update your plugin version.

**Comment by horrendo** [comment] 2023-11-22 18:38
Thanks. The query now works as long as I provide the namespace. Are there any plans to have it honour the current context?

**Comment by bigdatasourav** [comment] 2024-01-22 06:28
Hey, @horrendo, I have tried reproducing the `current-context` issue, but it works as expected.

My SPC - 
```
connection "kubernetes" {
  plugin    = "kubernetes"
  custom_resource_tables = ["*"]
}
```

```
➜  steampipe-plugin-kubernetes git:(main) kubectl config use-context gke_nagraj_us-central1-c_cluster-1
Switched to context "gke_nagraj_us-central1-c_cluster-1".
➜  steampipe-plugin-kubernetes git:(main) kubectl config current-context                       
gke_nagraj_us-central1-c_cluster-1
➜  steampipe-plugin-kubernetes git:(main) steampipe query                                                  
Welcome to Steampipe v0.21.3
For more information, type .help
> select name from kubernetes_node
+------------------------------------------+
| name                                     |
+------------------------------------------+
| gke-cluster-1-default-pool-1c435286-99wg |
+------------------------------------------+
> .quit
➜  steampipe-plugin-kubernetes git:(main) kubectl config use-context gke_nagraj_us-central1-c_cluster-2
Switched to context "gke_nagraj_us-central1-c_cluster-2".
➜  steampipe-plugin-kubernetes git:(main) kubectl config current-context                                   
gke_nagraj_us-central1-c_cluster-2
➜  steampipe-plugin-kubernetes git:(main) steampipe query                                                  
Welcome to Steampipe v0.21.3
For more information, type .help
> select name from kubernetes_node
+------------------------------------------+
| name                                     |
+------------------------------------------+
| gke-cluster-2-default-pool-1f53783a-szn3 |
+------------------------------------------+
```

Closing the issue now; please feel free to reopen it if you face the issue again.

**Closed by bigdatasourav** 2024-01-22 06:28 UTC
Labels: bug
